### ISSUE TITLE
DI Canary Failure

### ISSUE THREAD

**Issue by RosieCode95** [DiscordInjections/DiscordInjections#60]
Since the `React 16` update on Canary DI much broked. (this is a known issue im just reporting it)

```
Uncaught TypeError: Cannot read property 'createElement' of undefined
    at Object.<anonymous> (C:\discordCSS\DiscordInjections\DiscordInjections\DomReady\Views\SettingsGeneral.js:1:181)
    at Object.<anonymous> (C:\discordCSS\DiscordInjections\DiscordInjections\DomReady\Views\SettingsGeneral.js:53:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\discordCSS\DiscordInjections\DiscordInjections\DomReady\DISettings.js:3:25)
    at Object.<anonymous> (C:\discordCSS\DiscordInjections\DiscordInjections\DomReady\DISettings.js:93:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\discordCSS\DiscordInjections\DiscordInjections\DomReady\index.js:41:20)
    at Object.<anonymous> (C:\discordCSS\DiscordInjections\DiscordInjections\DomReady\index.js:58:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at <anonymous>:6:20
    at EventEmitter.electron.ipcRenderer.on (C:\Users\rose\AppData\Local\DiscordCanary\app-0.0.163\resources\electron.asar\renderer\init.js:52:28)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
```

**Comment by RosieCode95** [comment]
im a dumb, this is patched (blame git like i always do)
