### ISSUE TITLE
Installer doesn't work on macOS

### ISSUE THREAD

**Issue by tbodt** [DiscordInjections/DiscordInjections#64]

**Comment by cking** [comment]
there will be a new installer coming out soon.

**Comment by austinhuang0131** [comment]
Is it like this?

```
> discordinjections@3.0.2 inject /Users/student/DiscordInjections
> node install.js inject

Please choose your process from the list:
0. /Users/student/Downloads/Discord.app/Contents/MacOS/Discord (55887)
1. /Users/student/Downloads/Discord.app/Contents/Frameworks/Discord (55889, 55890, 55892)
Input: 0
Installing
Closing client...
An error has occurred. Error: Command failed: killall -9 /Users/student/Downloads/Discord.app/Contents/MacOS/Discord
No matching processes belonging to you were found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
Exiting with code 1
```
I'm using Canary tho

**Comment by cking** [comment]
Mac OS doesn't work out of the box. You need a special installer. Come to discord to get help.

**Comment by cking** [comment]
V4 will be coming with a new installer system. If anyone with Mac OS is willing to help post a comment or preferably contact me via discord

**Comment by cking** [comment]
and its implemented
